use db;
create table student(rollno int,name varchar(20),address varchar(20),maths int,physics int,computerscience int,total int);
insert into student values(1,'abu','kozhikode',100,80,90,270);
insert into student values(2,'anu','uk',100,80,90,270);
insert into student values(3,'aju','canada',100,100,100,300);
insert into student values(4,'manu','kochi',100,80,90,270);
insert into student values(5,'vani','banglore',100,80,90,270);
insert into student values(6,'abi','goa',100,80,90,270);
insert into student values(7,'lalu','kozhikode',100,80,90,270);
insert into student values(8,'abdu','bali',100,80,90,270);
insert into student values(9,'akash','pala',100,90,90,280);
insert into student values(10,'shibla','palakkad',100,80,100,280);
insert into student values(11,'varun','palakkad',100,80,100,280);
insert into student values(12,'adwaith','palakkad',100,80,100,280);
insert into student values(13,'reema','palakkad',100,80,100,280);
insert into student values(14,'sarag','palakkad',100,80,100,280);
select * from student;
select * from student where address='kozhikode' or address='korea';
alter table student add department varchar(20);
select * from student;
update student set department='mca' where rollno=1;
update student set department='mca' where rollno=2;
update student set department='mech' where rollno=3;
update student set department='mech' where rollno=4;
update student set department='mech' where rollno=5;
update student set department='mca' where rollno=6;
update student set department='eee' where rollno=7;
update student set department='mca' where rollno=8;
update student set department='mca' where rollno=9;
update student set department='mca' where rollno=10;
update student set department='eee' where rollno=11;
update student set department='mech' where rollno=12;
update student set department='eee' where rollno=13;
select * from student;
select name,department from student order by name desc;
select name,max(total) from student;
select name,min(total) from student;
select avg(computerscience) from student;
select sum(physics) from student;
update student set department='eeg' where rollno=5;
update student set department='eeg' where rollno=10;
update student set department='eeg' where rollno=8;
select name,rollno,department from student where department like '%g';
select rollno,name from student where name like 'a%';
alter table student drop total;
select * from student;
alter table student add total int;
update student set total=maths+physics+computerscience where rollno=1;
update student set total=maths+physics+computerscience where rollno=2;
update student set total=maths+physics+computerscience where rollno=3;
update student set total=maths+physics+computerscience where rollno=4;
update student set total=maths+physics+computerscience where rollno=5;
update student set total=maths+physics+computerscience where rollno=6;
update student set total=maths+physics+computerscience where rollno=7;
update student set total=maths+physics+computerscience where rollno=8;
update student set total=maths+physics+computerscience where rollno=9;
update student set total=maths+physics+computerscience where rollno=10;
update student set total=maths+physics+computerscience where rollno=11;
update student set total=maths+physics+computerscience where rollno=12;
update student set total=maths+physics+computerscience where rollno=13;
update student set total=maths+physics+computerscience where rollno=14;
select * from student; 
create view studentdetails as select rollno,name,total from student;
select * from studentdetails;
alter table student add age int;
alter table student add constraint c_student check (age);
update student set age=15 where rollno=1;
update student set age=15 where rollno=2;
update student set age=15 where rollno=3;
update student set age=15 where rollno=4;
update student set age=15 where rollno=5;
update student set age=25 where rollno=6;
update student set age=15 where rollno=7;
update student set age=25 where rollno=8;
update student set age=15 where rollno=9;
update student set age=15 where rollno=10;
update student set age=15 where rollno=11;
update student set age=15 where rollno=12;
update student set age=15 where rollno=13;
update student set age=15 where rollno=14;
select * from student;
delete from student where age=25;
select * from student;
select * from student where total=(select max(total) from student);
alter table student add adno varchar(20);
update student set adno=100 where rollno=2;
update student set adno=101 where rollno=3;
update student set adno=102 where rollno=4;
update student set adno=103 where rollno=5;
update student set adno=104 where rollno=7;
update student set adno=105 where rollno=9;
update student set adno=106 where rollno=11;
select * from student;
alter table student add email varchar(20);
update student set email="100@gmail.com" where rollno=2;
update student set email="101@gmail.com" where rollno=3;
update student set email="102@gmail.com" where rollno=4;
update student set email="103@gmail.com" where rollno=5;
update student set email="104@gmail.com" where rollno=7;
update student set email="105@gmail.com" where rollno=9;
update student set email="106@gmail.com" where rollno=11;
select * from student;
create table department1(dept_id int,dept_name varchar(20),loc_id int);
alter table student modify name varchar(20) not null;
alter table student modify adno int not null;
insert into department1 values(10,"mca",256);
insert into department1 values(11,"cs",257);
insert into department1 values(12,"mca",258);
insert into department1 values(13,"btech",259);
insert into department1 values(14,"mech",260);
select * from student;
select  rollno,name from student UNION select dept_id,dept_name from department1;
alter table student add constraint stud_pk primary key(rollno);
describe department1
alter table student add constraint fk_student foreign key(department) references department1(dept_name);
